version: '2'
services:
  app:
#    image: summary_changes
    build: .
    ports:
      - 8080:5000
    networks:
      - front
      - back
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "3"
  mongo:
    image: mongo
    ports:
      - 27017
    networks:
      - back
networks:
  front:
  back:
